"""Claras Python utilities: BitFlagArray/Bitty, typed tables, bit selection."""

__version__ = "0.1.0"

from .common import (
    get_first_or,
    get_first_or_default,
    ExceptionRaiser,
    ExcRaiser,
    AccessibleAry,
    iter_bits,
)
from .commonTyping import (
    INTEGER_TYPES,
    DTableFields,
    TypeTable,
    build_type_tbl,
    get_type_for_scalar,
    get_type_for_bit_count,
    get_type_for_array,
    get_as_signed,
    get_as_unsigned,
)
from .commonEncoding import (
    CommonNBitAry,
    CommonNBitSc,
    get_max_value,
    get_bit_count,
    get_bitmask,
    trim_leading_zero,
    get_number,
    get_bits,
    flip_enc,
    trim_trailing_zero,
    symbol_to_str,
    get_bit_flag_idx,
    bits_to_hex,
    hex_to_bits,
    build_bins_n_print,
    fmt_k_bits,
    arrange_bits,
    get_bitwise_entropy,
    get_defined_bits,
)
from .GenericTable import (
    TableFields,
    NpColDef,
    item_type_of,
    range_type_of,
    get_defs_from_table_type,
    dtype_from_fields,
    table_item_from_fields,
    table_range_from_type,
    Table,
    NpColTable,
)
from .QueryableTable import (
    Query,
    Constraint,
    ConstraintColumn,
    CCol,
    QueryableTable,
    QTblSpecialCol,
    Undefined,
    build_type_table,
)
from .Mulitslice import Multislice
from .BitFlagArray import (
    NBitArray,
    NBitAryOnly,
    BitFlagArray,
    Bitty,
    DefinedBit,
    SliceView,
    sliceTypes,
    slice_union,
    slice_intersection,
    slices_to_indices,
    indices_to_slices,
    normalize_key,
    get_slice_item_count,
    put_bits,
    merge_slices,
    limit_to_bit_count,
    revert_bit_slice,
    revert_bit_slice_multi,
    ndarray_to_slice_list,
    select_bits,
    select_bits_multi,
    invert_key,
    get_indices,
    index_array,
    set_index_array,
    clear_cache,
)

__all__ = [
    "get_first_or", "get_first_or_default", "ExceptionRaiser", "ExcRaiser", "AccessibleAry", "iter_bits",
    "INTEGER_TYPES", "DTableFields", "TypeTable", "build_type_tbl",
    "get_type_for_scalar", "get_type_for_bit_count", "get_type_for_array",
    "get_as_signed", "get_as_unsigned",
    "CommonNBitAry", "CommonNBitSc", "get_max_value", "get_bit_count", "get_bitmask",
    "trim_leading_zero", "get_number", "get_bits", "flip_enc", "trim_trailing_zero",
    "symbol_to_str", "get_bit_flag_idx", "bits_to_hex", "hex_to_bits",
    "build_bins_n_print", "fmt_k_bits", "arrange_bits", "get_bitwise_entropy", "get_defined_bits",
    "TableFields", "NpColDef", "item_type_of", "range_type_of", "get_defs_from_table_type",
    "dtype_from_fields", "table_item_from_fields", "table_range_from_type", "Table", "NpColTable",
    "Query", "Constraint", "ConstraintColumn", "CCol", "QueryableTable", "QTblSpecialCol",
    "Undefined", "build_type_table",
    "Multislice",
    "NBitArray", "NBitAryOnly", "BitFlagArray", "Bitty", "DefinedBit", "SliceView", "sliceTypes",
    "slice_union", "slice_intersection", "slices_to_indices", "indices_to_slices",
    "normalize_key", "get_slice_item_count", "put_bits", "merge_slices", "limit_to_bit_count",
    "revert_bit_slice", "revert_bit_slice_multi", "ndarray_to_slice_list",
    "select_bits", "select_bits_multi", "invert_key", "get_indices", "index_array",
    "set_index_array", "clear_cache",
]
